org.gradle.jvmargs=-Xmx3G -Dhttps.protocols=TLSv1.2,TLSv1.3 \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
org.gradle.daemon=false
org.gradle.configureondemand=true

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
forge_version=47.1.3
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03
fabric_loader_version=0.16.10
fabric_api_version=0.92.5+1.20.1

artifact_name = "ExtraBotany"
## Mod Properties
mod_id=extrabotany
mod_name=Extra Botany: Reburn
mod_license=MIT License
mod_version=1.9.2
mod_group_id=io.github.lounode.extrabotany
mod_logo=assets/extrabotany/textures/logo.png
mod_authors=Lounode(Author), ExtraMeteorP(Original)
mod_description=Popular botania addon comes back!\nFor higher minecraft version.

mod_credits=Urranium(Texture), Keletu(Armor Model)
## Dev Env
kubejs = false
item_manager = jei

## Depends
botania_version=1.20.1-448
botania_version_range=[1.20.1-448,)
patchouli_version=1.20.1-84.1
patchouli_version_range=[1.20.1-84.1,)
curios_version=5.4.2+1.20.1
curios_version_range=[1.20.1-5.4.2,)
eventwrapper_version=1.1.3
eventwrapper_version_range=[1.1.3,)

## Integration
jei_version=15.20.0.106
jei_version_range=[1.20.1-15.2.0.27,)

mantle_version=1.11.43
mantle_version_range=[1.11.43,)
tinkers_version=3.9.1.30
tinkers_version_range=[3.9.1.30,)

top_version=1.20.1-10.0.1-3
top_version_range=[1.20.1-10.0.1-3,)

kubejs_version=2001.6.5-build.16
kubejs_version_range=[2001.6.5-build.16,)
rhino_version=2001.2.2-build.18
rhino_version_range=[2001.2.2-build.18,)
architectury_version=9.1.12
architectury_version_range=[9.1.12,)
